# Generated by Django 5.2.7 on 2025-11-05 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('sentiment', models.CharField(choices=[('agreement', 'Agreement'), ('disagreement', 'Disagreement'), ('no_relation', 'No Relation')], default='no_relation', max_length=20)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
