# Generated by Django 5.2.7 on 2025-11-05 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('sentence', models.TextField()),
                ('relation', models.CharField(choices=[('agreement', 'Agreement'), ('disagreement', 'Disagreement'), ('no_relation', 'No Relation')], default='no_relation', max_length=20)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='sentence',
            options={},
        ),
        migrations.RenameField(
            model_name='sentence',
            old_name='text',
            new_name='sentence',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='sentiment',
        ),
    ]
