# Generated by Django 5.2.7 on 2025-11-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0002_sentiment_alter_sentence_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField()),
            ],
        ),
    ]
