# Generated by Django 5.2.7 on 2025-11-14 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0003_query'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='sentence',
            new_name='query',
        ),
        migrations.AlterField(
            model_name='sentiment',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentiments', to='query.query'),
        ),
        migrations.AlterField(
            model_name='sentiment',
            name='sentence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query.sentence'),
        ),
    ]
