# Generated by Django 5.2.7 on 2025-11-14 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0004_rename_sentence_query_query_alter_sentiment_query_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentiment',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_queries', to='query.query'),
        ),
        migrations.AlterField(
            model_name='sentiment',
            name='sentence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_sentences', to='query.sentence'),
        ),
    ]
